"""initial schema

Skema awal Family Health Monitor sesuai ERD.md.

Selain tabel, migrasi ini menyiapkan tiga hal yang tidak terdeteksi
autogenerate:
- ekstensi timescaledb & vector
- vitals_readings sebagai hypertable (ERD §2.7)
- index HNSW untuk similarity search embedding (ERD §2.13)

Langkah khusus Postgres dilewati pada dialect lain supaya test suite tetap
bisa jalan tanpa ekstensi terpasang.

Revision ID: 69c074b30f2e
Revises: 
Create Date: 2026-09-05 14:24:26.134051

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c074b30f2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if is_postgres():
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('default_unit', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('vital', 'derived', 'experimental', 'other')", name='ck_category_valid'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('is_dependent', sa.Boolean(), nullable=False),
    sa.Column('managed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['managed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activities_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('coffee', 'exercise', 'smoking', 'alcohol', 'sleep', 'meal', 'other')", name='ck_category_valid'),
    sa.CheckConstraint("source IN ('menu', 'chat')", name='ck_source_valid'),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_log_user_id'), 'activities_log', ['user_id'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('mean_value', sa.Numeric(), nullable=False),
    sa.Column('stddev_value', sa.Numeric(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metric_type'], ['metric_types.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_type', 'window_end', name='uq_baseline_window')
    )
    op.create_index(op.f('ix_baselines_user_id'), 'baselines', ['user_id'], unique=False)
    op.create_table('conversation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_log_user_id'), 'conversation_log', ['user_id'], unique=False)
    op.create_table('data_visibility_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_type IN ('vitals', 'activities', 'all')", name='ck_data_type_valid'),
    sa.CheckConstraint("visibility IN ('family', 'private')", name='ck_visibility_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_type', name='uq_visibility_per_type')
    )
    op.create_index(op.f('ix_data_visibility_settings_user_id'), 'data_visibility_settings', ['user_id'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('measurement_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('capture_method', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('signal_quality_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('signal_quality_flag', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("capture_method IN ('live', 'upload')", name='ck_capture_method_valid'),
    sa.CheckConstraint("processing_status IN ('pending', 'processing', 'completed', 'failed')", name='ck_processing_status_valid'),
    sa.CheckConstraint("signal_quality_flag IN ('good', 'fair', 'poor', 'rejected')", name='ck_signal_quality_flag_valid'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_sessions_user_id'), 'measurement_sessions', ['user_id'], unique=False)
    op.create_table('telegram_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_chat_id', sa.Text(), nullable=False),
    sa.Column('link_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measurement_session_id', sa.Uuid(), nullable=True),
    sa.Column('related_activity_id', sa.Uuid(), nullable=True),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.Numeric(), nullable=False),
    sa.Column('baseline_mean', sa.Numeric(), nullable=False),
    sa.Column('baseline_stddev', sa.Numeric(), nullable=False),
    sa.Column('deviation_score', sa.Numeric(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name='ck_severity_valid'),
    sa.CheckConstraint("status IN ('new', 'acknowledged', 'dismissed')", name='ck_status_valid'),
    sa.ForeignKeyConstraint(['measurement_session_id'], ['measurement_sessions.id'], ),
    sa.ForeignKeyConstraint(['metric_type'], ['metric_types.code'], ),
    sa.ForeignKeyConstraint(['related_activity_id'], ['activities_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_user_id'), 'anomalies', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system', 'tool')", name='ck_role_valid'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_role_valid'),
    sa.CheckConstraint("status IN ('active', 'removed')", name='ck_status_valid'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('health_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('fact_category', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("fact_category IN ('medical_history', 'allergy', 'symptom', 'family_history', 'medication', 'other')", name='ck_fact_category_valid'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversation_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_facts_user_id'), 'health_facts', ['user_id'], unique=False)
    op.create_table('video_storage_refs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('measurement_session_id', sa.Uuid(), nullable=False),
    sa.Column('storage_provider', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('encryption_key_ref', sa.Text(), nullable=True),
    sa.Column('retention_policy', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("storage_provider IN ('vps_local', 's3', 'minio')", name='ck_storage_provider_valid'),
    sa.ForeignKeyConstraint(['measurement_session_id'], ['measurement_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_session_id')
    )
    op.create_table('vitals_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('measurement_session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_session_id'], ['measurement_sessions.id'], ),
    sa.ForeignKeyConstraint(['metric_type'], ['metric_types.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'recorded_at')
    )
    op.create_index(op.f('ix_vitals_readings_measurement_session_id'), 'vitals_readings', ['measurement_session_id'], unique=False)
    op.create_index(op.f('ix_vitals_readings_metric_type'), 'vitals_readings', ['metric_type'], unique=False)
    op.create_index(op.f('ix_vitals_readings_user_id'), 'vitals_readings', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('anomaly_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('telegram', 'in_app')", name='ck_channel_valid'),
    sa.CheckConstraint("status IN ('sent', 'failed', 'pending')", name='ck_status_valid'),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###

    if is_postgres():
        # Hypertable hanya untuk vitals_readings; tabel lain volumenya kecil
        # dan bukan time-series murni (ERD note 6).
        op.execute(
            "SELECT create_hypertable('vitals_readings', 'recorded_at', "
            "migrate_data => TRUE)"
        )
        # HNSW dipilih ketimbang IVFFlat: tidak butuh training data, jadi
        # valid dibuat sejak tabel masih kosong.
        op.execute(
            "CREATE INDEX ix_health_facts_embedding ON health_facts "
            "USING hnsw (embedding vector_cosine_ops)"
        )

    _seed_metric_types()


def _seed_metric_types() -> None:
    """Seed ERD §2.6. Idempoten lewat ON CONFLICT DO NOTHING supaya
    perubahan lokal (mis. is_active) tidak ter-reset saat migrasi ulang."""
    from app.db.seed import SEED_METRIC_TYPES

    metric_types = sa.table(
        "metric_types",
        sa.column("code", sa.Text),
        sa.column("display_name", sa.Text),
        sa.column("default_unit", sa.Text),
        sa.column("category", sa.Text),
        sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    rows = [
        {**metric, "is_active": True, "created_at": sa.func.now()}
        for metric in SEED_METRIC_TYPES
    ]
    if is_postgres():
        from sqlalchemy.dialects.postgresql import insert as pg_insert

        stmt = pg_insert(metric_types).values(rows).on_conflict_do_nothing(
            index_elements=["code"]
        )
    else:
        stmt = metric_types.insert().values(rows)
    op.execute(stmt)


def downgrade() -> None:
    if is_postgres():
        op.execute("DROP INDEX IF EXISTS ix_health_facts_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_vitals_readings_user_id'), table_name='vitals_readings')
    op.drop_index(op.f('ix_vitals_readings_metric_type'), table_name='vitals_readings')
    op.drop_index(op.f('ix_vitals_readings_measurement_session_id'), table_name='vitals_readings')
    op.drop_table('vitals_readings')
    op.drop_table('video_storage_refs')
    op.drop_index(op.f('ix_health_facts_user_id'), table_name='health_facts')
    op.drop_table('health_facts')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_anomalies_user_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('telegram_links')
    op.drop_index(op.f('ix_measurement_sessions_user_id'), table_name='measurement_sessions')
    op.drop_table('measurement_sessions')
    op.drop_table('families')
    op.drop_index(op.f('ix_data_visibility_settings_user_id'), table_name='data_visibility_settings')
    op.drop_table('data_visibility_settings')
    op.drop_index(op.f('ix_conversation_log_user_id'), table_name='conversation_log')
    op.drop_table('conversation_log')
    op.drop_index(op.f('ix_baselines_user_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_activities_log_user_id'), table_name='activities_log')
    op.drop_table('activities_log')
    op.drop_table('users')
    op.drop_table('metric_types')
    # ### end Alembic commands ###
